name: New workflow


on:
 workflow_dispatch:

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: npm build
      run: npm run build

 test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: npm test
      run: npm test

 deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: npm deploy
      run: npm run deploy
